# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6ed2e725c4dd4c73549edd659666925085d1c6f1a437d80403e5d138dce2cf8cc1e5179d7dec7713f93d7c27e3261bacb7e2eb1a6f8cd1d7a1638093a89bdb1

test:
  secret_key_base: 57185debe9df0105ee80e0e2bc81a2f979568342344438ef397236d0631e9ee514a12d6c7c52d40e072d38bcf943acb96ea2e7ce1ae7a4a4f116b74b3a6756fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
